### PR TITLE
adding SkipTests atribute

### PR DESCRIPTION
**Pull request by tadams1138**
I added an attribute, SKipTests, that can be applied to a test class, test collection or assembly. It allows you to skip whole groups of tests with a single line. I've found this useful to mark out large groups of EF integration tests until I'm ready to modify EF related classes.

### CODE REVIEW

**Comment by AArnott** [comment]
Is the idea here that you would not check in use of these attributes to source code?

**Comment by tadams1138** [comment]
I've actually checked these attributes into source control. I've had need of an attribute like this to mark classes, collections and even assemblies to skip because the associated tests were integration tests. Perhaps I'm following a less-than-ideal practice, but I've found it useful to turn groups of tests on and off depending on whether I'm testing integration testing (e.g. verify EF models query from DB without error). I frequently find myself marking these test collections as skippable, only uncommenting the skip attribute locally but never committing the "uncomment" so that the CI/CD system never runs the integration tests. Your project has been the closest I've seen to accommodating my needs, so I thought I'd expand on it. It's been a busy week, but I hope that makes some sense. I welcome any feedback you can offer whether you think this a good addition or if you have any suggestions for how I should change my test strategy.

**Comment by AArnott** [comment]
Thanks for elaborating on your use case. I fill in this need using class and assembly level xunit Traits, then wherever I run tests, I use a filter to filter the tests with those traits out. For example, consider this file, which defines a test-level trait attribute, applies it, and also a test that gets tagged with it:

```cs
using System;
using Xunit;
using Xunit.Sdk;

[assembly: AssemblyTrait("SkipOnCI", "true")]

[TraitDiscoverer("Xunit.Sdk.TraitDiscoverer", "xunit.core")]
[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
public sealed class AssemblyTraitAttribute : Attribute, ITraitAttribute
{
    /// <summary>
    /// Creates a new instance of the <see cref="T:Xunit.TraitAttribute" /> class.
    /// </summary>
    /// <param name="name">The trait name</param>
    /// <param name="value">The trait value</param>
    public AssemblyTraitAttribute(string name, string value)
    {
    }
}


namespace XUnitTestProject4
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {

        }
    }
}
```

Then you can specify to your test runner to skip all tests where "SkipOnCI" is "true".
If you're using the VS test runner, you might need to use `"TestCategory", "SkipOnCI"` instead since it seems to like TestCategory names for traits.

I think that's a better fit than one that requires a source code change to change the sets of tests to run. What do you think?

**Comment by tadams1138** [comment]
I'll give that a try and get back to you. Many of my projects are based on .Net Core 1.0 (project.json stuff), so I vaguely recall something about that prevents me from using traits effectively. Many (most?) projects I encounter have a slower time-to-upgrade than the .Net Core timeline (waaaaay slower than your average JS framework, but I'll save you my JS-needs-to-slow-the-heck-down rant for another day). I'll let you know my experience after following your suggestions. Thanks for your input!

**Pull request closed without merging**
