### PR TITLE
Adding virtual and less restrictive access modifiers for reuse.

### PR DESCRIPTION
**Pull request by DavidRMaltby**
These are the minimal changes that I needed for reuse.  Thanks.

### CODE REVIEW

**Comment by DavidRMaltby** [comment]
Is there a system error here?  I'm not understanding the nature of the check failures here.

**Comment by AArnott** [comment]
You can see the build errors here: https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=2628&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=0f0b056b-e9f7-5ce7-8817-a8ca2fd77699

They may appear as _warnings_ in VS to you but warnings get promoted to errors in our PR validation to keep us warning clean.

**Comment by AArnott** [comment]
Before I push this to nuget.org, can you verify with [this CI build](https://dev.azure.com/andrewarnott/OSS/_packaging?_a=package&feed=PublicCI&package=Xunit.SkippableFact&protocolType=NuGet&version=1.4.6&view=overview) that it fully addresses your requirements?

**Comment by DavidRMaltby** [comment]
Andrew,
Definitely.  I’ll verify that here in the next hour or two.

Thanks,
David

**Comment by DavidRMaltby** [comment]
Andrew,
I have confirmed it.

[cid:image001.png@01D61A2C.DAF0DDB0]

Thank you for adding this into the repository.  It avoided me having to copy so much of your repo’s code.

Appreciate it!
David


From: Maltby, David
Sent: Friday, April 24, 2020 10:56 AM
To: AArnott/Xunit.SkippableFact <reply@reply.github.com>; AArnott/Xunit.SkippableFact <Xunit.SkippableFact@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [AArnott/Xunit.SkippableFact] Adding virtual and less restrictive access modifiers for reuse. (#18)

Andrew,
Definitely.  I’ll verify that here in the next hour or two.

Thanks,
David

**Pull request merged**
